languageCode = "se-SE"
title = "Träna på Högskoleprovet - Såhär blir du expert - Högskoleprovet.nu"
theme = "hpskolan"

baseURL = "https://www.högskoleprovet.nu/"

[params]
author = "HPSkolan"
logo = "images/featured_default.png"
header = "HPSkolan - Högskoleprovet.nu"
featuredImage = "images/featured_default.png"

facebook = "hogskoleprovet.nu"


[markup.goldmark.renderer]
unsafe = true
