languageCode = "se-SE"
title = "Träna på Högskoleprovet - Såhär blir du expert - Högskoleprovet.nu"
theme = "hpskolan"

baseURL = "https://d1iouh2uob27at.cloudfront.net/"

[params]
author = "HPSkolan"
logo = "images/featured_default.png"
header = "HPSkolan - Högskoleprovet.nu"
featuredImage = "images/featured_default.png"

facebook = "hogskoleprovet.nu"


[markup.goldmark.renderer]
unsafe = true

[deployment]

[[deployment.targets]]
name = "prod"
URL = "s3://hpskolan-public?region=eu-west-1"
cloudFrontDistributionID = "E382B3D2K2RXRS"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true